Django/developer/urls.py
from django.urls import path
from . import views
from .views import DevDetailVue
from .views import IndexView

app_name = 'developer'

urlpatterns = [
path('', IndexView.as_view(), name='index'),
path('<int:pk>', DevDetailVue.as_view(), name='detail'),
path('create', views.create, name='create'),
path('specifics/<int:developer_id>', views.delete, name='delete'),




]

Django/home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='index'),
]

Django/mproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('developer/', include('developer.urls')),
    path('task/', include('task.urls')),
    path('', include('home.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

Django/task/urls.py
from django.urls import path
from . import views
from .views import IndexView
app_name = 'task'

urlpatterns = [
path('', IndexView.as_view(), name='index'),
path('create', views.create, name='create'),
path('specifics/<int:task_id>', views.delete, name='delete'),





]

Django/developer/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class Developer(AbstractUser):
    first_name = models.CharField("first name", max_length=200)
    last_name = models.CharField(max_length=200)

    REQUIRED_FIELDS = ['first_name', 'last_name']

    def is_free(self):
        return self.tasks.count() == 0

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    is_free.boolean = True
    is_free.short_description = 'Is free'

Django/home/models.py
from django.db import models

# Create your models here.

Django/task/models.py
from django.db import models

from developer.models import Developer


class Task(models.Model):
    title = models.CharField(max_length=100, unique=True)
    description = models.TextField()
    assignee = models.ForeignKey(Developer, related_name="tasks",
                                 on_delete=models.CASCADE, null=True)

    class Meta:
        permissions = [
            ('task_management', 'Can create, assign and delete tasks'),
        ]

# Create your models here.

Django/developer/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

import task.forms
from developer.models import Developer


class DeveloperForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('first_name', 'last_name', 'username', 'email')


class DeveloperChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('first_name', 'last_name', 'username', 'email')


class ShortDeveloperForm(forms.ModelForm):
    class Meta:
        model = Developer
        fields = ['first_name', 'last_name', 'username']

Django/task/forms.py
from django import forms
from .models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'assignee']

Django/developer/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views.generic import DetailView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from task.forms import TaskForm
from .forms import ShortDeveloperForm
from .models import Developer


def index(request):
    context = {
        'developers': Developer.objects.all(),
        'form': ShortDeveloperForm,
    }
    return render(request, 'developer/index.html', context)


class DevDetailVue(DetailView):
    model = Developer
    template_name = 'developer/detail.html'

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        form = TaskForm(
            initial={'assignee': get_object_or_404(Developer, pk=self.kwargs['pk'])})
        form.fields['assignee'].disabled = True
        context['form'] = form
        return context


class IndexView(LoginRequiredMixin, ListView):
    model = Developer
    template_name = "developer/index.html"
    context_object_name = 'developers'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['form'] = ShortDeveloperForm
        return context


def create(request):
    form = ShortDeveloperForm(request.POST)
    if form.is_valid():
        Developer.objects.create_user(
            first_name=form.cleaned_data['first_name'],
            last_name=form.cleaned_data['last_name'],
            username=form.cleaned_data['username'],
        )
    return HttpResponseRedirect(reverse('developer:index'))


def delete(request, developer_id):
    Developer.objects.get(pk=developer_id).delete()
    return HttpResponseRedirect(reverse('developer:index'))

Django/home/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = "home/index.html"
# Create your views here.

Django/task/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views import generic
from django.views.generic import ListView

from .forms import TaskForm
from .models import Task


def index(request):
    context = {
        'tasks': Task.objects.all(),
    }
    return render(request, 'task/index.html', context)


class IndexView(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    model = Task
    template_name = "task/index.html"
    context_object_name = 'tasks'
    permission_required = 'task.task_management'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['form'] = TaskForm
        return context


def create(request):
    form = TaskForm(request.POST)
    if form.is_valid():
        Task.objects.create(
            title=form.cleaned_data['title'],
            description=form.cleaned_data['description'],
            assignee=form.cleaned_data['assignee']
        )
    return HttpResponseRedirect(reverse('task:index'))


def delete(request, task_id):
    Task.objects.get(pk=task_id).delete()
    return HttpResponseRedirect(reverse('task:index'))

# Create your views here.

Django/developer/templates/developer/_base.html
{% extends "_base.html" %}
{% block title %}GProject - Gestion des developpeurs{% endblock title %}
{% block Bigtitle %} Gestion des developpeurs{% endblock Bigtitle %}
{% block menu-script %}
$("#nav-home").removeClass('active')
$("#nav-dev").addClass('active')
$("#nav-task").removeClass('active')
{% endblock menu-script %}

Django/developer/templates/developer/_create_dev_modal.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% load crispy_forms_tags %}
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#add-dev-modal">Add user</button>
<!-- Ajout du modal contenant le formulaire -->
<div class="modal fade " id="add-dev-modal">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">New developer</h4>
                <button type="button" class="close" data-dismiss="modal"><i class="fa fa-close"></i></button>
            </div>
            <div class="modal-body">
                <form action="{% url 'developer:create' %}"
                      method="post">
                          {% csrf_token %}
                    {{ form|crispy }}
                    <div>
                        <button class="btn btn-primary"
                                type="submit">Créer
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
</body>
</html>

Django/developer/templates/developer/detail.html
{% extends "developer/_base.html" %}
<h1>MProject</h1>
<h2>Détail de {{ developer.first_name }}</h2>
{% block title %} Détail - {{ developer.first_name }} {{ developer.last_name }} {% endblock title %}
{% block content %}
    <div class="jumbotron" style="height:150px">
        <form action="{% url 'developer:delete' developer.id %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="close"><i class="fa fa-trash"></i></button>
        </form>
        <h1>{{ developer.first_name }} {{ developer.last_name }}</h1>
      <p>{{ developer.tasks.all|length }}
            tâche{{ developer.tasks.all|length|pluralize }}
            assignée{{ developer.tasks.all|length|pluralize }}</p>
    </div>
        <ul class="list-group">
            {% for tsk in developer.tasks.all %}
        <li class="list-group-item"> <strong>{{ tsk.title }}</strong>  {{ tsk.description }} </li>
        {% endfor %}
        </ul>
    <br>
      {% include 'task/_create_task_modal.html' %}
{% endblock content %}

Django/developer/templates/developer/index.html
{% extends "developer/_base.html" %}

<!DOCTYPE html>

<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, >
initial-scale=1.0">
    <title>MProject</title>
</head>
<body>
<h1>MProject</h1>
<h2>Liste des dévelopeurs</h2>

{% block title %} Liste des dévelopeurs {% endblock title %}
{% block content %}
    {% if developers %}
        <div class="container-sm l-3 d-flex flex-wrap border">
            {% for dev in developers %}
                <div class="card bg-primary m-2 p-1 rounded-lg"
                     style="width:300px">
                    <div class="card-title">
                        {{ dev.first_name }} {{ dev.last_name }}
                    </div>
                    <div class="card-body">
                        {{ dev.tasks.all|length }}
                        tâche{{ developer.tasks.all|length|pluralize }}
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'developer:detail' dev.id %}"
                           class="btn btn-outline-light">Détails</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <div class="container m-4">
            <alert class="alert alert-warning">Il n'y a aucun dévelopeur enregistré</alert>
        </div>
    {% endif %}
    {% include 'developer/_create_dev_modal.html' %}
{% endblock content %}

</body>

Django/home/templates/home/_base.html
{% extends "_base.html" %}
{% block title %}GProject - Gestion des developpeurs{% endblock title %}
{% block Bigtitle %} HOME{% endblock Bigtitle %}
{% block menu-script %}
$("#nav-home").addClass('active')
$("#nav-dev").removeClass('active')
$("#nav-task").removeClass('active')
{% endblock menu-script %}

Django/home/templates/home/index.html
{% extends "home/_base.html" %}
{% block content %}
    {% if user.is_authenticated %}
        <div class="p-1 m-3 bg-light">
            <p class="float-right"><a href={% url 'logout' %}>
               <i class="fas fa-sign-out-alt"></i></a></p>
            <h1>
                {{ user.first_name }} {{ user.last_name }}
            </h1>
        </div>
        <div class="container-sm">
            {% if user.tasks.all|length %}
                <ul class="list-group fluid">
                    {% for task in user.tasks.all %}
                        <li class="list-group-item">
                            <strong>{{ task.title }}</strong>
                            {{ task.description }}
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <alert class="alert alert-warning">No Tasks</alert>
            {% endif %}
        </div>
    {% else %}
        <h1>Coucou toi !</h1>
        <a href={% url 'login' %}>Log in</a>
    {% endif %}
{% endblock content %}

Django/task/templates/task/_base.html
{% extends "_base.html" %}
{% block title %}GProject - Gestion des tâches{% endblock title %}
{% block Bigtitle %} Gestion des tâches{% endblock Bigtitle %}
{% block menu-script %}
$("#nav-home").removeClass('active')
$("#nav-dev").removeClass('active')
$("#nav-task").addClass('active')
{% endblock menu-script %}

Django/task/templates/task/_create_task_modal.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% load crispy_forms_tags %}
{% if perms.task.task_management %}
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#add-dev-modal">Add Task</button>
<!-- Ajout du modal contenant le formulaire -->
<div class="modal fade " id="add-dev-modal">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">New Task</h4>
                <button type="button" class="close" data-dismiss="modal"><i class="fa fa-close"></i></button>
            </div>
            <div class="modal-body">
                <form
                        id="create-form"
                        onsubmit="$('#create-form *').removeAttr('disabled');"
                        action="{% url 'task:create' %}"
                        method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div>
                        <button class="btn btn-primary"
                                type="submit">Créer
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endif %}
</body>
</html>

Django/task/templates/task/index.html
{% extends "task/_base.html" %}

<!DOCTYPE html>

<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, >
initial-scale=1.0">
    <title>MProject</title>
</head>
<body>
{% block title %} Liste des tâches {% endblock title %}
{% block content %}
    {% if tasks %}
        <div class="container-sm l-3 d-flex flex-wrap border">
            {% for tsk in tasks %}
                <div class="card bg-primary m-2 p-1 rounded-lg"
                     style="width:300px">
                    <div class="card-title">
                        <p>Titre : {{ tsk.title }} </p>
                        <p>Description : {{ tsk.description }}</p>

                    </div>
                    <div class="card-body">
                        Pour : {{ tsk.assignee.first_name }} {{ tsk.assignee.last_name }}
                    </div>
                          <li class="list-group-item">
                    <form action="{% url 'task:delete' tsk.id %}" method="post">
                        {% csrf_token %}
                        <button class="close" type="submit"><i class="fa fa-trash"></i></button>
                    </form>
                </div>

            {% endfor %}
        </div>
    {% else %}
        <div class="container m-4">
            <alert class="alert alert-warning">Il n'y a aucune tâche assignée</alert>
        </div>
    {% endif %}
        {% include 'task/_create_task_modal.html' %}

{% endblock content %}

</body>
</html>

Django/templates/_base.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport">
    <title>{% block title %}MProject{% endblock title %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>

<div class="p-3 bg-primary">
    <h1 class="display-1">MProject</h1>
    <h2>{% block Bigtitle %}GProject - Gestion des developpeurs{% endblock Bigtitle %}</h2>
</div>

<nav class="navbar navbar-expand-sm bg-primary navbar-dark bordertop border-white">
    <ul class="navbar-nav">
        <li id="nav-home" class="nav-item">
            <a class="nav-link" href="{% url 'home:index' %}"><i class="fa fa-home bg"></i></a>
        </li>
        <li id="nav-dev" class="nav-item active">
            <a class="nav-link" href="{% url 'developer:index' %}">Developers</a>
        </li>
        <li id="nav-task" class="nav-item">
            <a class="nav-link" href="{% url 'task:index' %}">Tasks</a>
        </li>
    </ul>
</nav>
{% block content %}
{% endblock content %}
<script>
    {% block menu-script %}
        $("#nav-home").addClass('active')
        $("#nav-dev").removeClass('active')
        $("#nav-task").removeClass('active')
    {% endblock menu-script %}
</script>
</body>
</html>